// website/src/components/landing/CommandShowcase.tsx
"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { ScrollReveal } from "@/components/ui/ScrollReveal";
import { COMMANDS } from "@/lib/constants";
import { cn } from "@/lib/cn";

export function CommandShowcase() {
  const [activeTab, setActiveTab] = useState(0);

  return (
    <section className="py-24">
      <div className="mx-auto max-w-4xl px-6">
        <ScrollReveal>
          <SectionHeading
            title="Commands"
            subtitle="Create, switch, monitor, and clean up worktrees."
          />
        </ScrollReveal>

        <ScrollReveal className="mt-12">
          <div className="overflow-hidden rounded-xl border border-willow-border bg-willow-bg-code">
            <div className="flex items-stretch border-b border-willow-border bg-willow-bg-mute">
              <div className="flex items-center gap-2 px-4">
                <span className="h-3 w-3 rounded-full bg-willow-text-dim" />
                <span className="h-3 w-3 rounded-full bg-willow-text-dim" />
                <span className="h-3 w-3 rounded-full bg-willow-text-dim" />
              </div>
              <div className="flex flex-wrap">
                {COMMANDS.map((cmd, i) => (
                  <button
                    key={cmd.name}
                    onClick={() => setActiveTab(i)}
                    className={cn(
                      "border-b-2 px-5 py-3 font-mono text-xs font-medium transition-colors",
                      activeTab === i
                        ? "border-willow-accent text-willow-text-1"
                        : "border-transparent text-willow-text-3 hover:text-willow-text-1",
                    )}
                  >
                    {cmd.name}
                  </button>
                ))}
              </div>
            </div>

            <div className="p-5 font-mono text-sm leading-[1.7]">
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeTab}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.2 }}
                >
                  <div className="mb-2 text-willow-accent">
                    {COMMANDS[activeTab].command}
                  </div>
                  <pre className="whitespace-pre overflow-x-auto text-willow-text-2">
                    {COMMANDS[activeTab].output}
                  </pre>
                </motion.div>
              </AnimatePresence>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
}

// website/docs/.vitepress/theme/components/CommandShowcase.vue
<script setup lang="ts">
import { ref } from 'vue'

const activeTab = ref(0)

const commands = [
  {
    name: 'ww new',
    description: 'Create a worktree',
    command: '$ ww new feature/auth --no-fetch',
    output: `✨ Created worktree at ~/.willow/worktrees/myrepo/feature/auth
   Branch: feature/auth (from main)`,
  },
  {
    name: 'ww sw',
    description: 'Switch worktrees',
    command: '$ ww sw',
    output: `🤖 BUSY   auth-refactor     ~/.willow/worktrees/myrepo/auth-refactor
✅ DONE   api-cleanup       ~/.willow/worktrees/myrepo/api-cleanup
⏳ WAIT   payments          ~/.willow/worktrees/myrepo/payments
🟡 IDLE   main              ~/.willow/worktrees/myrepo/main`,
  },
  {
    name: 'ww ls',
    description: 'List worktrees',
    command: '$ ww ls',
    output: `  BRANCH               STATUS  PATH                                        AGE
  main                 IDLE    ~/.willow/worktrees/myrepo/main             3d
  auth-refactor        BUSY    ~/.willow/worktrees/myrepo/auth-refactor   2h
  payments             WAIT    ~/.willow/worktrees/myrepo/payments        1d`,
  },
  {
    name: 'ww status',
    description: 'Agent status',
    command: '$ ww status',
    output: `myrepo (3 worktrees, 2 agents active)

  🤖 auth-refactor          BUSY   2m ago
  ⏳ payments               WAIT   30s ago
  🟡 main                   IDLE   1h ago`,
  },
]
</script>

<template>
  <div class="command-showcase">
    <div class="showcase-chrome">
      <div class="chrome-bar">
        <div class="chrome-dots">
          <span class="chrome-dot"></span>
          <span class="chrome-dot"></span>
          <span class="chrome-dot"></span>
        </div>
        <div class="chrome-tabs">
          <button
            v-for="(cmd, i) in commands"
            :key="cmd.name"
            :class="['chrome-tab', { active: activeTab === i }]"
            @click="activeTab = i"
          >
            {{ cmd.name }}
          </button>
        </div>
      </div>
      <div class="showcase-body">
        <div class="showcase-line command-line">{{ commands[activeTab].command }}</div>
        <pre class="showcase-output">{{ commands[activeTab].output }}</pre>
      </div>
    </div>
  </div>
</template>

<style scoped>
.command-showcase {
  width: 100%;
}

.showcase-chrome {
  background: var(--willow-bg-code);
  border-radius: 12px;
  border: 1px solid var(--willow-border);
  overflow: hidden;
}

.chrome-bar {
  background: var(--willow-bg-mute);
  padding: 0 16px;
  display: flex;
  align-items: stretch;
  border-bottom: 1px solid var(--willow-border);
}

.chrome-dots {
  display: flex;
  align-items: center;
  gap: 8px;
  padding-right: 20px;
}

.chrome-dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: var(--willow-text-dim);
}

.chrome-tabs {
  display: flex;
  align-items: stretch;
  gap: 0;
}

.chrome-tab {
  background: transparent;
  border: none;
  border-bottom: 2px solid transparent;
  padding: 12px 20px;
  font-family: var(--vp-font-family-mono);
  font-size: 0.82rem;
  font-weight: 500;
  color: var(--willow-text-3);
  cursor: pointer;
  transition: color 0.2s ease-in-out, border-color 0.2s ease-in-out;
  position: relative;
}

.chrome-tab:hover {
  color: var(--willow-text-1);
}

.chrome-tab.active {
  color: var(--willow-text-1);
  border-bottom-color: var(--willow-accent);
}

.showcase-body {
  padding: 20px 24px;
  font-family: var(--vp-font-family-mono);
  font-size: 0.85rem;
  line-height: 1.7;
}

.command-line {
  color: var(--willow-accent);
  margin-bottom: 8px;
}

.showcase-output {
  color: var(--willow-text-2);
  margin: 0;
  white-space: pre;
  overflow-x: auto;
}

@media (max-width: 640px) {
  .chrome-tabs {
    flex-wrap: wrap;
  }

  .chrome-tab {
    padding: 10px 12px;
    font-size: 0.72rem;
  }

  .showcase-body {
    padding: 16px;
    font-size: 0.75rem;
  }
}
</style>
