// website/docs/.vitepress/theme/components/DirectoryTree.vue
<template>
  <div class="directory-tree">
    <div class="terminal-window">
      <div class="terminal-titlebar">
        <span class="terminal-dot"></span>
        <span class="terminal-dot"></span>
        <span class="terminal-dot"></span>
        <span class="terminal-title">~/.willow/</span>
      </div>
      <div class="tree-content">
        <div class="tree-line"><span class="tree-structure">~/.willow/</span></div>
        <div class="tree-line"><span class="tree-structure">├── </span><span class="tree-dir">repos/</span><span class="tree-annotation">bare clones (shared git database)</span></div>
        <div class="tree-line"><span class="tree-structure">│   └── </span><span class="tree-dir">myrepo.git/</span></div>
        <div class="tree-line"><span class="tree-structure">│       └── </span><span class="tree-file">willow.json</span><span class="tree-annotation">per-repo config</span></div>
        <div class="tree-line"><span class="tree-structure">├── </span><span class="tree-dir">worktrees/</span><span class="tree-annotation">isolated directories, one per branch</span></div>
        <div class="tree-line"><span class="tree-structure">│   └── </span><span class="tree-dir">myrepo/</span></div>
        <div class="tree-line"><span class="tree-structure">│       ├── </span><span class="tree-dir">main/</span></div>
        <div class="tree-line"><span class="tree-structure">│       ├── </span><span class="tree-dir">auth-refactor/</span><span class="tree-badge busy">BUSY</span></div>
        <div class="tree-line"><span class="tree-structure">│       └── </span><span class="tree-dir">payments/</span><span class="tree-badge wait">WAIT</span></div>
        <div class="tree-line"><span class="tree-structure">├── </span><span class="tree-dir">status/</span><span class="tree-annotation">Claude Code agent status</span></div>
        <div class="tree-line"><span class="tree-structure">│   └── </span><span class="tree-dir">myrepo/</span></div>
        <div class="tree-line"><span class="tree-structure">│       ├── </span><span class="tree-file">auth-refactor.json</span></div>
        <div class="tree-line"><span class="tree-structure">│       └── </span><span class="tree-file">payments.json</span></div>
        <div class="tree-line"><span class="tree-structure">└── </span><span class="tree-dir">hooks/</span><span class="tree-annotation">hook scripts</span></div>
        <div class="tree-line"><span class="tree-structure">    └── </span><span class="tree-file">claude-status-hook.sh</span></div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.tree-content {
  padding: 20px 24px;
  font-family: var(--vp-font-family-mono);
  font-size: 0.85rem;
  line-height: 1.8;
}

.tree-line {
  display: flex;
  align-items: center;
  gap: 0;
  white-space: nowrap;
}

.tree-structure {
  color: var(--willow-text-dim);
}

.tree-dir {
  color: var(--willow-accent);
  font-weight: 600;
}

.tree-file {
  color: var(--willow-text-2);
}

.tree-annotation {
  color: var(--willow-text-3);
  font-style: italic;
  margin-left: 16px;
  font-size: 0.8rem;
}

.tree-badge {
  font-size: 0.65rem;
  font-weight: 700;
  padding: 1px 8px;
  border-radius: 9999px;
  margin-left: 12px;
  letter-spacing: 0.05em;
}

.tree-badge.busy {
  background: rgba(248, 113, 113, 0.06);
  color: var(--willow-status-busy);
  border: 1px solid rgba(248, 113, 113, 0.12);
}

.tree-badge.wait {
  background: rgba(251, 191, 36, 0.06);
  color: var(--willow-status-wait);
  border: 1px solid rgba(251, 191, 36, 0.12);
}

@media (max-width: 640px) {
  .tree-content {
    font-size: 0.72rem;
    padding: 16px;
    overflow-x: auto;
  }

  .tree-annotation {
    display: none;
  }
}
</style>

// website/src/components/ui/DirectoryTree.tsx
import { TerminalWindow } from "./TerminalWindow";

const TREE_LINES = [
  { structure: "~/.willow/", dir: "", file: "", annotation: "" },
  {
    structure: "├── ",
    dir: "repos/",
    file: "",
    annotation: "bare clones (shared git database)",
  },
  { structure: "│   └── ", dir: "myrepo.git/", file: "", annotation: "" },
  {
    structure: "│       └── ",
    dir: "",
    file: "willow.json",
    annotation: "per-repo config",
  },
  {
    structure: "├── ",
    dir: "worktrees/",
    file: "",
    annotation: "isolated directories, one per branch",
  },
  { structure: "│   └── ", dir: "myrepo/", file: "", annotation: "" },
  { structure: "│       ├── ", dir: "main/", file: "", annotation: "" },
  {
    structure: "│       ├── ",
    dir: "auth-refactor/",
    file: "",
    annotation: "",
    badge: "busy" as const,
  },
  {
    structure: "│       └── ",
    dir: "payments/",
    file: "",
    annotation: "",
    badge: "wait" as const,
  },
  {
    structure: "├── ",
    dir: "status/",
    file: "",
    annotation: "Claude Code agent status",
  },
  { structure: "│   └── ", dir: "myrepo/", file: "", annotation: "" },
  {
    structure: "│       ├── ",
    dir: "",
    file: "auth-refactor.json",
    annotation: "",
  },
  {
    structure: "│       └── ",
    dir: "",
    file: "payments.json",
    annotation: "",
  },
  {
    structure: "└── ",
    dir: "hooks/",
    file: "",
    annotation: "hook scripts",
  },
  {
    structure: "    └── ",
    dir: "",
    file: "claude-status-hook.sh",
    annotation: "",
  },
] as const;

const BADGE_STYLES = {
  busy: "bg-status-busy/[0.06] text-status-busy border-status-busy/[0.12]",
  wait: "bg-status-wait/[0.06] text-status-wait border-status-wait/[0.12]",
} as const;

export function DirectoryTree() {
  return (
    <TerminalWindow title="~/.willow/">
      <div className="p-5 font-mono text-sm leading-[1.8]">
        {TREE_LINES.map((line, i) => (
          <div key={i} className="flex items-center whitespace-nowrap">
            <span className="text-willow-text-dim">{line.structure}</span>
            {line.dir && (
              <span className="font-semibold text-willow-accent">
                {line.dir}
              </span>
            )}
            {line.file && (
              <span className="text-willow-text-2">{line.file}</span>
            )}
            {"badge" in line && line.badge && (
              <span
                className={`ml-3 rounded-full border px-2 py-px text-[0.65rem] font-bold tracking-wider ${BADGE_STYLES[line.badge]}`}
              >
                {line.badge.toUpperCase()}
              </span>
            )}
            {line.annotation && (
              <span className="ml-4 hidden text-xs italic text-willow-text-3 sm:inline">
                {line.annotation}
              </span>
            )}
          </div>
        ))}
      </div>
    </TerminalWindow>
  );
}
