// website/docs/.vitepress/theme/components/HowItWorks.vue
<template>
  <div class="how-it-works">
    <div class="step" v-for="(step, i) in steps" :key="i">
      <div class="step-number">{{ i + 1 }}</div>
      <div class="step-content">
        <h3 class="step-title">{{ step.title }}</h3>
        <p class="step-desc">{{ step.description }}</p>
        <code class="step-command">{{ step.command }}</code>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const steps = [
  {
    title: 'Clone',
    description: 'Set up a repo for worktree-first workflow with a single command.',
    command: 'ww clone git@github.com:org/repo.git',
  },
  {
    title: 'Create worktrees',
    description: 'Spin up isolated directories for each task. Start Claude Code in each.',
    command: 'wwn feature/auth && claude',
  },
  {
    title: 'Monitor agents',
    description: 'See all your agents at a glance. Switch between them with fzf.',
    command: 'ww status',
  },
]
</script>

<style scoped>
.how-it-works {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24px;
}

.step {
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-divider);
  border-radius: 12px;
  padding: 28px 24px;
  position: relative;
  transition: border-color 0.2s ease-in-out;
}

.step:hover {
  border-color: var(--willow-border-hover);
}

.step-number {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: var(--willow-accent);
  color: var(--willow-bg);
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--vp-font-family-mono);
  font-weight: 700;
  font-size: 0.8rem;
  margin: 0 auto 16px;
}

.step-title {
  font-family: var(--vp-font-family-heading);
  font-weight: 600;
  font-size: 1.1rem;
  color: var(--willow-text-1);
  margin-bottom: 8px;
  text-align: center;
}

.step-desc {
  color: var(--willow-text-2);
  font-size: 0.9rem;
  line-height: 1.6;
  margin-bottom: 16px;
  text-align: center;
}

.step-command {
  display: block;
  background: var(--willow-bg-code);
  border: 1px solid var(--willow-border);
  border-radius: 6px;
  padding: 8px 12px;
  font-family: var(--vp-font-family-mono);
  font-size: 0.8rem;
  color: var(--willow-accent);
  overflow-x: auto;
  white-space: nowrap;
  text-align: center;
}

@media (max-width: 768px) {
  .how-it-works {
    grid-template-columns: 1fr;
  }
}
</style>

// website/src/components/landing/HowItWorks.tsx
"use client";

import { motion } from "framer-motion";
import { staggerContainer, fadeUp } from "@/lib/animations";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { ScrollReveal } from "@/components/ui/ScrollReveal";
import { STEPS } from "@/lib/constants";

export function HowItWorks() {
  return (
    <section className="py-24">
      <div className="mx-auto max-w-6xl px-6">
        <ScrollReveal>
          <SectionHeading
            title="How it works"
            subtitle="Three steps from clone to isolated local sessions."
          />
        </ScrollReveal>

        <motion.div
          variants={staggerContainer}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-80px" }}
          className="relative mt-16 grid gap-6 md:grid-cols-3"
        >
          <div className="absolute top-14 left-[16.67%] right-[16.67%] hidden h-px md:block">
            <motion.div
              className="h-full bg-gradient-to-r from-transparent via-willow-accent/30 to-transparent"
              initial={{ scaleX: 0 }}
              whileInView={{ scaleX: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 1, delay: 0.5, ease: "easeOut" }}
            />
          </div>

          {STEPS.map((step, i) => (
            <motion.div
              key={step.title}
              variants={fadeUp}
              className="relative rounded-2xl border border-willow-border bg-willow-bg-soft p-7 transition-colors hover:border-willow-border-hover"
            >
              <div className="mx-auto mb-4 flex h-8 w-8 items-center justify-center rounded-full bg-willow-accent font-mono text-sm font-bold text-willow-bg">
                {i + 1}
              </div>
              <h3 className="text-center font-heading text-lg font-semibold text-willow-text-1">
                {step.title}
              </h3>
              <p className="mt-2 text-center text-sm text-willow-text-2">
                {step.description}
              </p>
              <code className="mt-4 block overflow-x-auto whitespace-nowrap rounded-lg border border-willow-border bg-willow-bg-code px-3 py-2 text-center font-mono text-xs text-willow-accent">
                {step.command}
              </code>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
